name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Create File
        run: ssh -o StricktHostKeyChecking=no azureuser@48.217.49.228
      - name: Enter passphrase for (stdin):azure
        run: ssh-add -azure touch hello.txt